name: Build flask app using Reusable template
# Find the build template on the url below.
# https://github.com/mhassaankhokhar/reusable-templates/blob/master/.github/workflows/build-template.yml

on:
  push:
    branches:
      - master
jobs:
  build:
    uses: mhassaankhokhar/reusable-templates/.github/workflows/build-template.yml@master
    with:
      docker-image-name: "mhassaankhokhar/test"
    secrets:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASS: ${{secrets.DOCKER_PASS}}

deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh ubuntu@${{ secrets.HOST }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          # Stop and remove existing container if exists
          docker rm -f flask || true

          # Pull latest image
          docker pull your-dockerhub-username/your-image:latest

          # Run container on port 5000
          docker run -d \
            --name flask \
            -p 5000:5000 \
            --restart unless-stopped \
            your-dockerhub-username/your-image:latest
        EOF